services:
  fr24front:
    image: nginx:1.28.0-alpine
    container_name: fr24front
    restart: unless-stopped
    volumes:
      - ./frontend/html/:/usr/share/nginx/html:ro
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - fr24back
      - cloudflared

  fr24back:
    image: python:3.12-alpine
    container_name: fr24back
    restart: unless-stopped
    working_dir: /usr/src
    volumes:
      - ./backend/:/usr/src
    environment:
      - DUMP1090_HOST=${DUMP1090_HOST}
      - DUMP1090_PORT=${DUMP1090_PORT}
      - FR24BACK_LOG_UPDATE=${FR24BACK_LOG_UPDATE}
      - DEBUG_MODE=${DEBUG_MODE}
      - PYTHONUNBUFFERED=1
    command: sh -c "pip install -r requirements.txt && python backend_server.py"

  cloudflared:
    image: cloudflare/cloudflared:2025.10.0
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run vuelos
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
