version: "3.8"
services:
  fr24front:
    image: nginx:stable-alpine
    container_name: fr24front
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./frontend/html/:/usr/share/nginx/html:ro
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - fr24back

  fr24back:
    image: python:3.12-alpine
    container_name: fr24back
    restart: unless-stopped
    working_dir: /usr/src
    ports:
      - "5000:5000"
    volumes:
      - ./backend/:/usr/src
    environment:
      - DUMP1090_HOST=${DUMP1090_HOST}
      - DUMP1090_PORT=${DUMP1090_PORT}
      - FR24BACK_LOG_UPDATE=${FR24BACK_LOG_UPDATE}
      - DEBUG_MODE=${DEBUG_MODE}
      - PYTHONUNBUFFERED=1
    command: sh -c "pip install -r requirements.txt && python backend_server.py"
